export type NodeStatus = 'locked' | 'available' | 'in_progress' | 'completed'

export interface StoryNode {
  id: string
  label: string
  description: string
  x: number // 0–100 (% of canvas)
  y: number // 0–100 (% of canvas)
  status: NodeStatus
  completion: number // 0–100
  isBranching: boolean
  isStart?: boolean
  mainTask: string
  subtasks: string[]
}

export interface TreeEdge {
  from: string
  to: string
}

export interface NodeTreeData {
  nodes: StoryNode[]
  edges: TreeEdge[]
}

export const campaignData: NodeTreeData = {
  nodes: [
    {
      id: 'n1',
      label: 'První večeře',
      description: 'Start kampaně',
      x: 50,
      y: 8,
      status: 'completed',
      completion: 100,
      isBranching: false,
      isStart: true,
      mainTask: 'Špagety aglio e olio',
      subtasks: ['Jednoduchý salát', 'Česnekový chléb'],
    },
    {
      id: 'n2',
      label: 'Základní techniky',
      description: 'Nůž, pánev, trouba',
      x: 50,
      y: 24,
      status: 'in_progress',
      completion: 60,
      isBranching: false,
      mainTask: 'Francouzská omeleta',
      subtasks: ['Blanšírovaná zelenina', 'Redukce balsamic'],
    },
    {
      id: 'n3',
      label: 'Odstěhování',
      description: 'Čas se postavit na vlastní nohy',
      x: 50,
      y: 40,
      status: 'available',
      completion: 0,
      isBranching: true,
      mainTask: 'Nákup a plánování jídelníčku',
      subtasks: ['Organizace lednice'],
    },
    {
      id: 'n4',
      label: 'Sólo cesta',
      description: 'Vařím jen pro sebe',
      x: 25,
      y: 56,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Rychlé jednoporcové jídlo',
      subtasks: ['Meal prep na týden', 'Levný a výživný oběd'],
    },
    {
      id: 'n5',
      label: 'S partnerem',
      description: 'Vaříme spolu',
      x: 75,
      y: 56,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Romantická večeře pro dva',
      subtasks: ['Domácí těstoviny', 'Dezert pro dva'],
    },
    {
      id: 'n6',
      label: 'První večírek',
      description: 'Hosté přichází!',
      x: 50,
      y: 72,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Tříchodové menu pro šest',
      subtasks: ['Jednohubky na uvítanou', 'Míchaný drink'],
    },
    {
      id: 'n7',
      label: 'Mistr kuchyně',
      description: 'Závěrečná zkouška',
      x: 50,
      y: 88,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Vlastní autorský recept',
      subtasks: ['Fusion pokrm', 'Food styling a prezentace'],
    },
    {
      id: 'n8',
      label: 'Studentská kuchyně',
      description: 'Levně a chytře',
      x: 10,
      y: 70,
      status: 'locked',
      completion: 0,
      isBranching: true,
      mainTask: 'Jednohrncové rizoto',
      subtasks: ['Luštěninový salát'],
    },
    {
      id: 'n9',
      label: 'Noční vaření',
      description: 'Když máš hlad o půlnoci',
      x: -8,
      y: 84,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Rychlý ramen',
      subtasks: ['Marinované vejce'],
    },
    {
      id: 'n10',
      label: 'Meal prep',
      description: 'Příprava na celý týden',
      x: 18,
      y: 90,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Krabičky na 5 dní',
      subtasks: ['Pečená zelenina', 'Jogurtový dip'],
    },
    {
      id: 'n11',
      label: 'Gastro přežití',
      description: 'Krizový režim v kuchyni',
      x: -20,
      y: 102,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Jídlo do 15 minut',
      subtasks: ['Express pomazánka'],
    },
    {
      id: 'n12',
      label: 'Komfortní klasiky',
      description: 'Jídla, co vždy fungují',
      x: 5,
      y: 112,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Zapečené těstoviny',
      subtasks: ['Křupavý topping'],
    },
    {
      id: 'n13',
      label: 'Večeře pro dva',
      description: 'Lepší plating, lepší chuť',
      x: 90,
      y: 70,
      status: 'locked',
      completion: 0,
      isBranching: true,
      mainTask: 'Kuře na bylinkách',
      subtasks: ['Bramborové pyré'],
    },
    {
      id: 'n14',
      label: 'Asijský týden',
      description: 'Aromata a wok',
      x: 108,
      y: 84,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Stir-fry s nudlemi',
      subtasks: ['Rychlá omáčka'],
    },
    {
      id: 'n15',
      label: 'Domácí pekař',
      description: 'Trouba jako parťák',
      x: 82,
      y: 92,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Focaccia',
      subtasks: ['Bylinkový olej'],
    },
    {
      id: 'n16',
      label: 'Hostina u přátel',
      description: 'Více chodů bez chaosu',
      x: 122,
      y: 104,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Menu na večer',
      subtasks: ['Předkrm do ruky', 'Lehký dezert'],
    },
    {
      id: 'n17',
      label: 'Kulinářský podpis',
      description: 'Vlastní styl na talíři',
      x: 95,
      y: 114,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Autorský hlavní chod',
      subtasks: ['Omáčka od nuly'],
    },
    {
      id: 'n18',
      label: 'Regionální chutě',
      description: 'České klasiky moderně',
      x: 8,
      y: 42,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Květákové karbanátky',
      subtasks: ['Bylinkový dip'],
    },
    {
      id: 'n19',
      label: 'Street food mise',
      description: 'Jídlo do ruky',
      x: 92,
      y: 42,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Domácí tortilla wrap',
      subtasks: ['Pikantní salsa'],
    },
    {
      id: 'n20',
      label: 'Fermentační laboratoř',
      description: 'Chuť, která zraje',
      x: -12,
      y: 54,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Rychlé pickles',
      subtasks: ['Kvašená zelenina'],
    },
    {
      id: 'n21',
      label: 'Gril & plamen',
      description: 'Venkovní vaření',
      x: 112,
      y: 54,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Grilovaná zelenina a maso',
      subtasks: ['Domácí marináda'],
    },
    {
      id: 'n22',
      label: 'Sváteční stůl',
      description: 'Když se schází rodina',
      x: 50,
      y: 106,
      status: 'locked',
      completion: 0,
      isBranching: true,
      mainTask: 'Tříchodové menu',
      subtasks: ['Organizace přípravy'],
    },
    {
      id: 'n23',
      label: 'Lehký směr',
      description: 'Fresh a fit přístup',
      x: 34,
      y: 120,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Bowl s quinoou',
      subtasks: ['Citrusový dressing'],
    },
    {
      id: 'n24',
      label: 'Poctivý směr',
      description: 'Sytá domácí jídla',
      x: 66,
      y: 120,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Pomalu tažené ragú',
      subtasks: ['Domácí noky'],
    },
    {
      id: 'n25',
      label: 'Legendární finále',
      description: 'Vrchol celého stromu',
      x: 50,
      y: 134,
      status: 'locked',
      completion: 0,
      isBranching: true,
      mainTask: 'Degustační menu',
      subtasks: ['Signature dezert', 'Párování chutí'],
    },
    {
      id: 'n26',
      label: 'Experimentální větev',
      description: 'Odvážné kombinace',
      x: 78,
      y: 138,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Fusion challenge',
      subtasks: ['Neobvyklé suroviny'],
    },
    {
      id: 'n27',
      label: 'Tradiční větev',
      description: 'Klasika dotažená k dokonalosti',
      x: 22,
      y: 138,
      status: 'locked',
      completion: 0,
      isBranching: false,
      mainTask: 'Recept po generace',
      subtasks: ['Ruční příprava těsta'],
    },
  ],
  edges: [
    { from: 'n1', to: 'n2' },
    { from: 'n2', to: 'n3' },
    { from: 'n3', to: 'n18' },
    { from: 'n3', to: 'n19' },
    { from: 'n18', to: 'n20' },
    { from: 'n19', to: 'n21' },
    { from: 'n3', to: 'n4' },
    { from: 'n3', to: 'n5' },
    { from: 'n4', to: 'n8' },
    { from: 'n8', to: 'n9' },
    { from: 'n8', to: 'n10' },
    { from: 'n9', to: 'n11' },
    { from: 'n10', to: 'n12' },
    { from: 'n5', to: 'n13' },
    { from: 'n13', to: 'n14' },
    { from: 'n13', to: 'n15' },
    { from: 'n14', to: 'n16' },
    { from: 'n15', to: 'n17' },
    { from: 'n4', to: 'n6' },
    { from: 'n5', to: 'n6' },
    { from: 'n6', to: 'n7' },
    { from: 'n7', to: 'n22' },
    { from: 'n22', to: 'n23' },
    { from: 'n22', to: 'n24' },
    { from: 'n23', to: 'n25' },
    { from: 'n24', to: 'n25' },
    { from: 'n25', to: 'n26' },
    { from: 'n25', to: 'n27' },
  ],
}
